gui:
  sidePanelWidth: 0.4
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  wrapLinesInStagingView: false

  showFileTree: false
  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false

  promptToReturnFromSubprocess: false

